env: "gymma"

env_args:
  key: null
  time_limit: 25
  pretrained_wrapper: null

test_greedy: True
test_nepisode: 1000
test_interval: 5000
log_interval: 5000
runner_log_interval: 1000
learner_log_interval: 1000
t_max: 500000
